# Generated by Django 5.0.6 on 2024-06-14 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carro_imagem'),
        ('cliente', '0002_cliente_nivel_bruto_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
            preserve_default=False,
        ),
    ]
