# Generated by Django 5.0.6 on 2024-06-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_compra_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='valor',
        ),
    ]
